# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'terminal' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for terminal

  

  platform :ios, '9.0'
  target 'terminalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'terminal-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for terminal-tvOS

  target 'terminal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
