# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'terminal' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for terminal

  

  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
